# Generated by Django 5.1.4 on 2025-01-11 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_count', models.IntegerField()),
                ('char_count', models.IntegerField()),
                ('char_count_no_spaces', models.IntegerField()),
                ('sentence_count', models.IntegerField()),
                ('avg_word_length', models.FloatField()),
                ('word_frequency', models.JSONField()),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='analyzer.document')),
            ],
        ),
    ]
